# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: kintsu
networks:
- id: 10143
  start_block: 0
  contracts:
  - name: StakedMonad
    address:
    - 0x07AabD925866E8353407E67C1D157836f7Ad923e
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: Compounded(uint256 amount)
    - event: EIP712DomainChanged()
    - event: FeesAdjusted(uint256 newFee)
    - event: FeesWithdrawn(uint256 shares)
    - event: NodeAdded(address nodeId, uint256 index)
    - event: NodeRemoved(address nodeId)
    - event: NodeUpdated(address indexed nodeId, uint256 oldWeight, uint256 newWeight)
    - event: RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)
    - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
    - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
    - event: Staked(address indexed staker, uint256 amount, uint256 newShares)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
    - event: UnlockCancelled(address indexed staker, uint256 unlockId)
    - event: UnlockRedeemed(address indexed staker, uint256 unlockId, uint256 amount)
    - event: UnlockRequested(address indexed staker, uint256 unlockId, uint256 shares)
    - event: UnlockSent(uint256 batchId, uint256 shares, uint256 spotValue)
